per-hour portod.log rotation fixed
Commit 699a31a10b0cd9998e468eb008a5d56fad34f86e upstream.

when called directly via crontab (/var/log has root:syslog creds):
error: skipping "/var/log/portod.log" because parent directory has insecure permissions